homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_altitude

  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret timezone
  # Customization file
  customize: !include_dir_merge_named customizations/
  
  # Authorisation
  auth_providers:
  - type: homeassistant
  - type: trusted_networks
    trusted_networks:
      - 127.0.0.1
      - ::1
      - 192.168.86.0/24
      - fd00::/8

#logger:

system_health:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

# Frontend integrations
# panel_iframe:
#   influxdb:
#     title: InfluxDB
#     icon: mdi:chart-areaspline
#     url: !secret influxdb_url

panel_custom:
  - name: hassio-main
    sidebar_title: Configurator
    sidebar_icon: mdi:wrench
    js_url: /api/hassio/app/entrypoint.js
    url_path: configurator
    embed_iframe: true
    require_admin: true
    config:
      ingress: "core_configurator"

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret base_url
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
  ip_ban_enabled: true
  login_attempts_threshold: 5


# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

api:

alexa:
  smart_home:

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# IFTTT
ifttt:
  key: !secret ifttt_key

# Cameras
ffmpeg:
camera: !include_dir_merge_list cameras/

#vacuum:
#  - platform: xiaomi_miio
#    host: 192.168.86.29
#    name: Donut the Vacuum
#    token: 

 #- platform: synology
 #   url: http://timsnas:5001
 #   username: !secret synology_user
 #   password: !secret synology_password
 #   verify_ssl: false

influxdb: !include influxdb.yaml

# Zones
zone: !include zones.yaml

# Device Tracker
device_tracker: !include device_tracker.yaml

# Inputs
input_select: !include_dir_merge_named inputs/select
input_number: !include_dir_merge_named inputs/number
input_datetime: !include_dir_merge_named inputs/datetime
input_boolean: !include_dir_merge_named inputs/boolean

# Lights
light: !include lights.yaml

# Sensors
sensor:  !include_dir_merge_list sensors/

# Binary Sensors
binary_sensor:  !include_dir_merge_list binary_sensors/

# Switches
switch: !include_dir_merge_list switches/

# Timers
timer: !include_dir_merge_named timers/

# Groups
group: !include_dir_merge_named groups/

# Scripts
script: !include_dir_merge_named scripts/

# Shell Commands
shell_command: !include_dir_merge_named shell_commands/

# Automations
automation: !include_dir_merge_list automations/

#group: !include groups.yaml
#shell_command: !include shell_commands.yaml
#automation: !include automations.yaml
#script: !include scripts.yaml

# Sensors
#sensor: !include sensors.yaml
#binary_sensor: !include binary_sensors.yaml